package styles

import (
	"github.com/eastym/chroma/v2"
)

// RainbowDash style.
var Research = Register(chroma.MustNewStyle("research", chroma.StyleEntries{
	chroma.Comment:                  "italic #0080ff",
	chroma.CommentPreproc:           "noitalic #fff",
	chroma.CommentSpecial:           "bold",
	chroma.Error:                    "bg:#cc0000 #ffffff",
	chroma.GenericDeleted:           "border:#c5060b bg:#ffcccc",
	chroma.GenericEmph:              "italic",
	chroma.GenericError:             "#ff0000",
	chroma.GenericHeading:           "bold #2c5dcd",
	chroma.GenericInserted:          "border:#00cc00 bg:#ccffcc",
	chroma.GenericOutput:            "#aaaaaa",
	chroma.GenericPrompt:            "bold #2c5dcd",
	chroma.GenericStrong:            "bold",
	chroma.GenericSubheading:        "bold #2c5dcd",
	chroma.GenericTraceback:         "#c5060b",
	chroma.GenericUnderline:         "underline",
	chroma.Keyword:                  "bold #2c5dcd",
	chroma.KeywordPseudo:            "nobold",
	chroma.KeywordType:              "#5918bb",
	chroma.NameAttribute:            "#000",
	chroma.NameBuiltin:              "#000",
	chroma.NameBuiltinPseudo:        "#000",
	chroma.NameClass:                "#000",
	chroma.NameConstant:             "#000",
	chroma.NameDecorator:            "#000",
	chroma.NameEntity:               "#000",
	chroma.NameException:            "#000",
	chroma.NameFunction:             "#000",
	chroma.NameFunctionMagic:        "#000",
	chroma.NameKeyword:              "#000",
	chroma.NameLabel:                "#000",
	chroma.NameNamespace:            "#000",
	chroma.NameOperator:             "#000",
	chroma.NameOther:                "#000",
	chroma.NamePseudo:               "#000",
	chroma.NameProperty:             "#000",
	chroma.NameTag:                  "#000",
	chroma.NameVariable:             "#000",
	chroma.NameVariableAnonymous:    "#000",
	chroma.NameVariableClass:        "#000",
	chroma.NameVariableGlobal:       "#000",
	chroma.NameVariableInstance:     "#000",
	chroma.NameVariableMagic:        "bold #2c5dcd",
	chroma.LiteralNumber:            "bold #5918bb",
	chroma.Operator:                 "#2c5dcd",
	chroma.OperatorWord:             "bold",
	chroma.LiteralStringAffix:       "#000",
	chroma.LiteralStringAtom:        "#000",
	chroma.LiteralStringBacktick:    "#000",
	chroma.LiteralStringBoolean:     "#000",
	chroma.LiteralStringChar:        "#000",
	chroma.LiteralStringDelimiter:   "#000",
	chroma.LiteralStringDoc:         "#000",
	chroma.LiteralStringDouble:      "#000",
	chroma.LiteralStringEscape:      "#000",
	chroma.LiteralStringHeredoc:     "#000",
	chroma.LiteralStringInterpol:    "#000",
	chroma.LiteralStringName:        "#000",
	chroma.LiteralStringOther:       "#000",
	chroma.LiteralStringRegex:       "#000",
	chroma.LiteralStringSingle:      "#000",
	chroma.LiteralStringSymbol:      "bold #c5060b",
	chroma.LiteralNumberBin:         "#000",
	chroma.LiteralNumberFloat:       "#000",
	chroma.LiteralNumberHex:         "#000",
	chroma.LiteralNumberInteger:     "#000",
	chroma.LiteralNumberIntegerLong: "#000",
	chroma.LiteralNumberOct:         "#000",
	chroma.Text:                     "#4d4d4d",
	chroma.TextWhitespace:           "#cbcbcb",
	chroma.TextPunctuation:          "#0f0",
	chroma.Punctuation: 				"#f00",
	chroma.Background:               " bg:#000",
}))
