package styles

import (
	"github.com/eastym/chroma/v2"
)

// RainbowDash style.
var Research = Register(chroma.MustNewStyle("research", chroma.StyleEntries{
	//	chroma.Comment:                  "italic #0080ff",
	//	chroma.CommentPreproc:           "noitalic #fff",
	//	chroma.CommentHashbang:          "#fff",
	chroma.CommentMultiline: "#fff",
	chroma.CommentSingle:    "#fff",
	//	chroma.CommentSpecial:           "bold",
	// chroma.Error:              "bg:#cc0000 #ffffff",
	// chroma.GenericDeleted:     "border:#c5060b bg:#ffcccc",
	// chroma.GenericEmph:        "italic",
	// chroma.GenericError:       "#ff0000",
	// chroma.GenericHeading:     "bold #2c5dcd",
	// chroma.GenericInserted:    "border:#00cc00 bg:#ccffcc",
	// chroma.GenericOutput:      "#aaaaaa",
	// chroma.GenericPrompt:      "bold #2c5dcd",
	// chroma.GenericStrong:      "bold",
	// chroma.GenericSubheading:  "bold #2c5dcd",
	// chroma.GenericTraceback:   "#c5060b",
	// chroma.GenericUnderline:   "underline",
	chroma.Keyword:            "#fff",
	chroma.KeywordConstant:    "#fff",
	chroma.KeywordDeclaration: "#fff",
	chroma.KeywordNamespace:   "#fff",
	//	chroma.KeywordPseudo:            "#fff",
	//	chroma.KeywordReserved:          "#fff",
	chroma.KeywordType: "#000",
	//chroma.NameAttribute:            "#fff",
	chroma.NameBuiltin: "#f0f", // make append  len string
	// chroma.NameBuiltinPseudo:        "#fff",
	chroma.NameClass:    "#fff",
	chroma.NameConstant: "#fff",
	//chroma.NameDecorator:     "#fff",
	//chroma.NameEntity:        "#fff",
	//chroma.NameException:     "#fff",
	chroma.NameFunction: "#0f0",
	//chroma.NameFunctionMagic: "#fff",
	//chroma.NameKeyword:       "#fff",
	//chroma.NameLabel:         "#fff",
	//chroma.NameNamespace:     "#fff",
	//chroma.NameOperator:      "#fff",
	chroma.NameOther: "#fff",
	//chroma.NamePseudo:               "#fff",
	//chroma.NameProperty:             "#fff",
	//chroma.NameTag:                  "#fff",
	chroma.NameVariable: "#fff",
	//chroma.NameVariableAnonymous:    "#fff",
	//chroma.NameVariableClass:        "#fff",
	//chroma.NameVariableGlobal:       "#fff",
	//chroma.NameVariableInstance:     "#fff",
	chroma.NameVariableMagic: "bold #2c5dcd",
	chroma.LiteralNumber:     "bold #5918bb",
	chroma.Operator:          "#99d",
	//chroma.OperatorWord:      "bold #f00",
	//chroma.LiteralStringAffix:       "#fff",
	//chroma.LiteralStringAtom:        "#fff",
	//chroma.LiteralStringBacktick:    "#fff",
	//chroma.LiteralStringBoolean:     "#fff",
	//chroma.LiteralStringChar:        "#fff",
	//chroma.LiteralStringDelimiter:   "#fff",
	//chroma.LiteralStringDoc:         "#fff",
	//chroma.LiteralStringEscape:      "#fff",
	chroma.LiteralStringHeredoc: "#fff",
	//chroma.LiteralStringInterpol: "#fff",
	chroma.LiteralStringName:  "#fff",
	chroma.LiteralStringOther: "#fff",
	//chroma.LiteralStringRegex:    "#fff",
	chroma.LiteralStringSingle:  "#fff",
	chroma.LiteralStringSymbol:  "bold #c5060b",
	chroma.LiteralString:        "#fff",
	chroma.LiteralNumberBin:     "#fff",
	chroma.LiteralNumberFloat:   "#fff",
	chroma.LiteralNumberHex:     "#fff",
	chroma.LiteralNumberInteger: "#fff",
	//chroma.LiteralNumberIntegerLong: "#fff",
	chroma.LiteralNumberOct: "#fff",
	chroma.Text:             "#fff",
	chroma.TextWhitespace:   "#cbcbcb",
	// chroma.TextPunctuation:          "#0f0",
	chroma.Punctuation: "#f00", //
	chroma.Bracket:     "#00f",
	chroma.Background:  " bg:#fff",
}))
